typography_spectrum: 0.847587
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.297149
  lightness: 0.433114
  rhythmicContrast: 0.649122
  saturation: 0.74671
opengraph: {}
layout_spectrum: 0.34978
analytics: {}
name: zepp
cta: {}
title: hello
description: wsup
purpose: {}
